default:
  http_metas:
    content-type: text/html

  metas:
    title:        Pumukit Explore
    robots:       index, follow
    description:  Edit data base of Pumukit
    keywords:     pumukit, BBDD
    language:     es

  stylesheets:    [main]

  javascripts:    []

  has_layout:     on
  layout:         layout
