default:
  has_layout:     on
  layout:         layout

previewallSuccess:
  stylesheets:    [tv/default, css]

all:
  stylesheets:    [/sf/calendar/calendar-system.css, /sf/calendar/skins/aqua/theme.css, admin/accordion.css, admin/tree, admin/jquery-ui.css] 
  javascripts:    [jwplayer, /sf/calendar/calendar.js, /sf/calendar/lang/calendar-es.js, /sf/calendar/calendar-setup.js, jquery-1.9.0.js, jquery-ui-1.10.0.custom.min.js, jquery.jstree.js, AC_OETags, swfobject, jquery.jstree.js, jquery.cookie.js, jquery.hotkeys.js]

